/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Client: typeof import('./src/views/user/client.vue')['default']
    Command: typeof import('./src/views/user/command.vue')['default']
    Home: typeof import('./src/views/user/home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./src/views/user/sign-up.vue')['default']
    User: typeof import('./src/views/user/index.vue')['default']
  }
}
