<script lang="ts" setup>
import { useRouter } from 'vue-router';
import Avatar from 'primevue/avatar';
import Menu from '@/src/components/menu.vue';
import History from '@/src/components/history.vue';
import socials from '@/src/components/socials.vue';
import { useOrderStore } from '@/src/store/order.store';
import { ref } from 'vue';
const router = useRouter()
function reachProfile() {
  router.push({ name: "user-me" })
}
const currentPage = ref("menu")

const options = [
  {
    title: "Menu",
    name: 'menu'
  },
  {
    title: "Historique",
    name: 'history'
  },
  {
    title: "Reactions",
    name: 'social'
  },
]
</script>

<template>
  <div class="relative h-full ">
    <div class="flex items-center  ">
      <div class="text-xl px-4 py-4 grow">The wiyao</div>
      <span @click="reachProfile">
        <Avatar class="mr-4" shape="circle" />
      </span>
    </div>


    <div class="space-x-4 px-4">
      <button v-for="(item, index) in options" :key="index" @click="() => currentPage = item.name"
        :class="{ 'text-black rounded-full bg-gray-200 px-5 py-1': currentPage === item.name }" class="">{{ item.title
        }}</button>

    </div>
    <Menu v-if="currentPage === 'menu'"></Menu>
    <History v-if="currentPage === 'history'"></History>
    <socials v-if="currentPage === 'social'"></socials>

  </div>
</template>

<style scoped>
.snackShadow {
  box-shadow: 0px 10px 5px #dcdcdc, 0px -10px 5px #DCDCDC69;
}

h1 {
  font-weight: 500;
  font-size: 2.6rem;
  top: -10px;
}

h3 {
  font-size: 1.2rem;
}

.green {
  margin-top: 20px;
}

.scale-in-ver-bottom {
  -webkit-animation: scale-in-ver-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  animation: scale-in-ver-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-4-25 9:29:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-in-ver-bottom
 * ----------------------------------------
 */
@-webkit-keyframes scale-in-ver-bottom {
  0% {
    -webkit-transform: scaleY(0);
    transform: scaleY(0);
    -webkit-transform-origin: 0% 100%;
    transform-origin: 0% 100%;
    opacity: 1;
  }

  100% {
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
    -webkit-transform-origin: 0% 100%;
    transform-origin: 0% 100%;
    opacity: 1;
  }
}

@keyframes scale-in-ver-bottom {
  0% {
    -webkit-transform: scaleY(0);
    transform: scaleY(0);
    -webkit-transform-origin: 0% 100%;
    transform-origin: 0% 100%;
    opacity: 1;
  }

  100% {
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
    -webkit-transform-origin: 0% 100%;
    transform-origin: 0% 100%;
    opacity: 1;
  }
}
</style>
