<script lang="ts" setup>
import { useRouter } from 'vue-router';
import Avatar from 'primevue/avatar';
import type { Item } from '@/src/data/models/items';
import { useOrderStore } from '@/src/store/order.store';
const orderStore = useOrderStore()
const router = useRouter()
import _ from "lodash"
function reachCommands() {
  router.push({ name: "user-commands" })
}
function reachProfile() {
  router.push({ name: "user-me" })
}

const menu: Item[] = [
  {
    id: "37fee742-785a-4302-bba7-5092ce6e3089",
    description: "Montre-bracelet, dite “d'Aviateur”, métal inaltérable, diam. 435ym. Mouvement de précision chronographe, cadran avec grande aiguille trotteuse, permettant la lecture 1/25de seconde.",
    likes: 12,
    name: "Ayimolou",
    price: 1000,
    images: []
  },
  {
    id: "37fee742-785a-4302-bba7-5092ce6e30800",
    description: "Montre-bracelet, dite “d'Aviateur”, métal inaltérable, diam. 435ym. Mouvement de précision chronographe, cadran avec grande aiguille trotteuse, permettant la lecture 1/25de seconde.",
    likes: 12,
    name: "Ema koumé",
    price: 2000,
    images: []
  }
]

function addItemToOrder(menu: Item) {
  const index = _.findIndex(orderStore.currentOrder, { id: menu.id })
  if (index === -1) {
    orderStore.currentOrder.push(menu)
  } else {
    _.remove(orderStore.currentOrder, { id: menu.id })
  }
}
function isSelected(id: string): boolean {
  const index = _.findIndex(orderStore.currentOrder, { id: id })
  return index !== -1;
}

</script>

<template>
  <div class="relative h-full ">
    <div class="flex items-center  ">
      <div class="text-xl px-4 py-4 grow">The wiyao</div>
      <span @click="reachProfile">
        <Avatar class="mr-4" shape="circle" />
      </span>
    </div>


    <div class="space-x-4 px-4">
      <button class=" text-black rounded-full bg-gray-100 px-5 py-1 ">Menu</button>
      <button class="">Historique</button>
      <button>Social</button>
    </div>

    <div class="px-4 pt-5 relative">
      <p class="text-xs text-gray-300 animate-none pb-2 ">Touchez pour ajouter au panier</p>
      <div class="space-y-3 overflow-y-auto ">


        <div
          class="flex justify-start items-start px-4 py-2  border w-full rounded-lg overflow-clip duration-500 transition"
          :class="{ 'bg-gray-200 shadow-xl': isSelected(item.id) }" @click="addItemToOrder(item)"
          v-for="(item, index) in menu" :key="index">
          <img src="https://primefaces.org/cdn/primevue/images/galleria/galleria7.jpg" alt="Image"
            class="rounded-lg w-14 h-14" />
          <div class="px-4">
            <p>{{ item.name }} - <span>{{ item.price }} Fcfa</span></p>
            <p class="prose prose-red text-xs">{{ item.description }} </p>
            <div class="space-x-2">
              <!-- <span class="text-xs rounded-xl px-3 py-1"> <v-icon name="fa-regular-heart"></v-icon> {{ item.likes }}</span> -->
              <span class="text-xs rounded-xl px-3 py-1"> <v-icon name="fa-regular-hand-peace"></v-icon> {{ item.likes
              }}</span>
              <!-- <span class="text-xs rounded-xl px-3 py-1"> <v-icon name="fa-regular-hand-peace"></v-icon> 10</span> -->

            </div>
          </div>
        </div>


        <div class="flex   w-full rounded-lg overflow-clip h-32 justify-center text-center">
          <p class="text-xs text-gray-300 ">vous êtes à la fin de la liste </p>
        </div>
      </div>

    </div>
    <!-- <Transition appear> -->
    <div v-if="orderStore.currentOrder.length != 0" class="bottom-0 fixed text-white bg-black transition duration-700"
      @click="reachCommands">
      <div class="flex  w-screen shadow-teal-300 items-center  h-16 justify-center snackShadow">
        <div class="pr-4 pl-4"> <v-icon name="fa-info"></v-icon> </div>
        <div class="w-full  justify-center">
          <p>Vous avez {{ orderStore.currentOrder.length }} commandes en attente </p>
          <p>Continuer </p>
        </div>
        <div class="pr-4"> <v-icon name="fa-chevron-right"></v-icon> </div>
      </div>
    </div>
    <!-- </Transition> -->
  </div>
</template>

<style scoped>
.snackShadow {
  box-shadow: 0px 10px 5px #dcdcdc, 0px -10px 5px #DCDCDC69;
}

h1 {
  font-weight: 500;
  font-size: 2.6rem;
  top: -10px;
}

h3 {
  font-size: 1.2rem;
}

.green {
  margin-top: 20px;
}

.scale-in-ver-bottom {
  -webkit-animation: scale-in-ver-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  animation: scale-in-ver-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-4-25 9:29:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-in-ver-bottom
 * ----------------------------------------
 */
@-webkit-keyframes scale-in-ver-bottom {
  0% {
    -webkit-transform: scaleY(0);
    transform: scaleY(0);
    -webkit-transform-origin: 0% 100%;
    transform-origin: 0% 100%;
    opacity: 1;
  }

  100% {
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
    -webkit-transform-origin: 0% 100%;
    transform-origin: 0% 100%;
    opacity: 1;
  }
}

@keyframes scale-in-ver-bottom {
  0% {
    -webkit-transform: scaleY(0);
    transform: scaleY(0);
    -webkit-transform-origin: 0% 100%;
    transform-origin: 0% 100%;
    opacity: 1;
  }

  100% {
    -webkit-transform: scaleY(1);
    transform: scaleY(1);
    -webkit-transform-origin: 0% 100%;
    transform-origin: 0% 100%;
    opacity: 1;
  }
}</style>
